/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lib_managment_sys;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.JOptionPane;

import javax.swing.JOptionPane;

import javax.swing.JOptionPane;

/**
 *
 * @author kashi
 */
public class liberarian extends javax.swing.JFrame {

    /**
     * Creates new form liberarian
     */
    public liberarian() {
        initComponents();
         Image icon=new ImageIcon(this.getClass().getResource("/library.png")).getImage();
        this.setIconImage(icon);
        titlelbl.setFocusable(rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlelbl = new javax.swing.JLabel();
        catbtn = new javax.swing.JButton();
        memberbtn = new javax.swing.JButton();
        issuebtn = new javax.swing.JButton();
        authorbtn = new javax.swing.JButton();
        publisherbtn = new javax.swing.JButton();
        returnbtn = new javax.swing.JButton();
        booksbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        biling = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LIBERARY MANAGMENT SYSTEM\n");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelbl.setBackground(new java.awt.Color(255, 255, 255));
        titlelbl.setFont(new java.awt.Font("Lucida Fax", 1, 37)); // NOI18N
        titlelbl.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl.setText("Liberary Managment System");
        jPanel1.add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 570, 60));

        catbtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        catbtn.setText("Category");
        catbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        catbtn.setMaximumSize(new java.awt.Dimension(72, 23));
        catbtn.setMinimumSize(new java.awt.Dimension(72, 23));
        catbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catbtnActionPerformed(evt);
            }
        });
        jPanel1.add(catbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 140, 30));

        memberbtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        memberbtn.setText("Members");
        memberbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        memberbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberbtnActionPerformed(evt);
            }
        });
        jPanel1.add(memberbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 140, 30));

        issuebtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        issuebtn.setText("Issue Book");
        issuebtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        issuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebtnActionPerformed(evt);
            }
        });
        jPanel1.add(issuebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 140, 30));

        authorbtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        authorbtn.setText("Authors");
        authorbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        authorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorbtnActionPerformed(evt);
            }
        });
        jPanel1.add(authorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 140, 30));

        publisherbtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        publisherbtn.setText("Publishers");
        publisherbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        publisherbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherbtnActionPerformed(evt);
            }
        });
        jPanel1.add(publisherbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 140, 30));

        returnbtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        returnbtn.setText("Return Book");
        returnbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 140, 30));

        booksbtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        booksbtn.setText("Books");
        booksbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        booksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksbtnActionPerformed(evt);
            }
        });
        jPanel1.add(booksbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 30));

        logoutbtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        logoutbtn.setText("Log out");
        logoutbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 100, 30));

        biling.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        biling.setText("Billing");
        biling.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        biling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilingActionPerformed(evt);
            }
        });
        jPanel1.add(biling, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catbtnActionPerformed
        Category ct=new Category();
        
        ct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_catbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
      int option=  JOptionPane.showConfirmDialog(rootPane, "are you sure.", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if ( option==JOptionPane.YES_OPTION) {
              new   loginpage().setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void authorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorbtnActionPerformed
        Author auth=new Author();
        auth.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_authorbtnActionPerformed

    private void publisherbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherbtnActionPerformed
        new Publisher().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_publisherbtnActionPerformed

    private void booksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksbtnActionPerformed
       new Books().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_booksbtnActionPerformed

    private void memberbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberbtnActionPerformed
       new Member().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_memberbtnActionPerformed

    private void issuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebtnActionPerformed
       new IssueBook().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_issuebtnActionPerformed

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        new ReturnBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnbtnActionPerformed

    private void bilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilingActionPerformed
        
        new Billing().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bilingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new liberarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorbtn;
    private javax.swing.JButton biling;
    private javax.swing.JButton booksbtn;
    private javax.swing.JButton catbtn;
    private javax.swing.JButton issuebtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton memberbtn;
    private javax.swing.JButton publisherbtn;
    private javax.swing.JButton returnbtn;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
